1. Vecter, Matrix and Tensor

- 3D Tensor in NLP : (batch size, 문장 길이, 단어 벡터의 차원)

2. Making Tenser for Numpy

- 1D with Numpy

In [ ]:
import numpy as np

In [ ]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [ ]:
t.ndim

1

In [ ]:
t.shape

(7,)

- 2D with Numpy

In [ ]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [ ]:
t.ndim

2

In [ ]:
t.shape

(4, 3)

3. Pytorch Tensor Allocation

In [ ]:
import torch

- 1D with PyTorch

In [ ]:
t = torch.FloatTensor([0.,1.,2.,3.])
t

tensor([0., 1., 2., 3.])

In [ ]:
t.dim()

1

In [ ]:
t.shape

torch.Size([4])

In [ ]:
t[-1]

tensor(3.)

- 2D  with PyTorch

In [ ]:
t = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
t.shape

torch.Size([2, 3])

In [ ]:
t[:,1]

tensor([2., 5.])

In [ ]:
t[:,1].shape

torch.Size([2])

In [ ]:
t[1]

tensor([4., 5., 6.])

In [ ]:
t[:,:-1]

tensor([[1., 2.],
        [4., 5.]])

- Broadcasting : 자동으로 크기 맞춰 연산 수행

In [ ]:
t1 = torch.FloatTensor([[1,2]])
t2 = torch.FloatTensor([3])
t1 + t2

tensor([[4., 5.]])

4. 자주 사용되는 기능들

- Matrix Multiplication Vs. Multiplication

  - matmul()

In [ ]:
t1 = torch.FloatTensor([[1,2],[3,4]])
t2 = torch.FloatTensor([[1],[2]]) # 2 x 1

t1.matmul(t2)

tensor([[ 5.],
        [11.]])

  - * or mul()

In [ ]:
t1 * t2

tensor([[1., 2.],
        [6., 8.]])

- Mean

In [ ]:
t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
t.mean()

tensor(2.5000)

In [ ]:
t.mean(dim = 0) # dim = 0: 첫 차원 제거

tensor([2., 3.])

In [ ]:
t.mean(dim = 1) # dim = 1: 두 번째 차원 제거

tensor([1.5000, 3.5000])

In [ ]:
t.mean(dim = -1) # 마지막 차원 제거

- Sum

In [ ]:
t.sum()

tensor(10.)

In [ ]:
t.sum(dim = 0)

tensor([4., 6.])

- Max

In [ ]:
t.max()

tensor(4.)

In [ ]:
t.max(dim = 0) # result에서 index [1,1] return

torch.return_types.max(values=tensor([3., 4.]), indices=tensor([1, 1]))

In [ ]:
print('Max: ',t.max(dim = 0)[0])
print('ArgMax: ',t.max(dim = 0)[1])

Max:  tensor([3., 4.])
ArgMax:  tensor([1, 1])


5. View : 원소의 수 유지하며 텐서 크기 변경

In [ ]:
t = np.array([[[0,1,2],
             [3,4,5]],
             [[6,7,8],
              [9,10,11]]])
f = torch.FloatTensor(t)
f.shape

torch.Size([2, 2, 3])

- 3D Tensor -> 2D Tensor

In [ ]:
f.view([-1,3]) # -1은 파이토치에 맡기겠다는 의미

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [ ]:
f.view([-1,3]).shape

torch.Size([4, 3])

- 3D Tensor 상에서 크기 변경

In [ ]:
f.view([-1,1,3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [ ]:
f.view([-1,1,3]).shape

torch.Size([4, 1, 3])

7. Squeeze : 1인 차원 제거

In [ ]:
f = torch.FloatTensor([[0],[1],[2]])
f.squeeze()

tensor([0., 1., 2.])

8. Unsqueeze : 특정 위치에 1인 차원 추가

In [ ]:
f = torch.Tensor([0,1,2])
f.unsqueeze(0)

tensor([[0., 1., 2.]])

In [ ]:
f.unsqueeze(0).shape

torch.Size([1, 3])

In [ ]:
f.view(1,-1)

tensor([[0., 1., 2.]])

9. Type Casting

In [ ]:
t = torch.LongTensor([1,2,3,4])
t.float()

tensor([1., 2., 3., 4.])

In [ ]:
t = torch.ByteTensor([True,False,False,True])
t.long()

tensor([1, 0, 0, 1])

10. concatenate

In [ ]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
torch.cat([x,y],dim=0) # 첫 번째 차원을 늘리자

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [ ]:
torch.cat([x,y],dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

11. Stacking

In [ ]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [ ]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

12. ones_like and zeros_like

In [ ]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

13. In-place Operation

In [ ]:
x.mul_(2.)
x # _를 붙이면 연산 결과값으로 바뀐다. 

tensor([[0., 2., 4.],
        [4., 2., 0.]])