### - nn.Module로 선형 회귀 구현

1. 단순 선형 회귀

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

model = nn.Linear(1,1) # input_dim = 1, output_dim = 1

list(model.parameters()) # parameter 랜덤 초기화

[Parameter containing:
 tensor([[0.7118]], requires_grad=True), Parameter containing:
 tensor([0.2852], requires_grad=True)]

In [ ]:
optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  h = model(x_train)
  cost = F.mse_loss(h, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 6.355488
Epoch  100/2000 Cost: 0.045163
Epoch  200/2000 Cost: 0.027908
Epoch  300/2000 Cost: 0.017245
Epoch  400/2000 Cost: 0.010657
Epoch  500/2000 Cost: 0.006585
Epoch  600/2000 Cost: 0.004069
Epoch  700/2000 Cost: 0.002515
Epoch  800/2000 Cost: 0.001554
Epoch  900/2000 Cost: 0.000960
Epoch 1000/2000 Cost: 0.000593
Epoch 1100/2000 Cost: 0.000367
Epoch 1200/2000 Cost: 0.000227
Epoch 1300/2000 Cost: 0.000140
Epoch 1400/2000 Cost: 0.000087
Epoch 1500/2000 Cost: 0.000053
Epoch 1600/2000 Cost: 0.000033
Epoch 1700/2000 Cost: 0.000020
Epoch 1800/2000 Cost: 0.000013
Epoch 1900/2000 Cost: 0.000008
Epoch 2000/2000 Cost: 0.000005


In [ ]:
model(torch.FloatTensor([[4.0]])) # training 후 입력이 4일때 예측값

tensor([[7.9956]], grad_fn=<AddmmBackward0>)

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9975]], requires_grad=True), Parameter containing:
 tensor([0.0058], requires_grad=True)]

2. 다중 선형 회귀

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

model = nn.Linear(3,1) # input_dim = 3, output_dim = 1

optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)
# 1e-5 = 0.00001, 0.01로 하지 않는 이유는 기울기가 발산하기 때문이다. 

nb_epochs = 2000
for epoch in range(nb_epochs+1):
    h = model(x_train)
    cost = F.mse_loss(h, y_train) 

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 40791.382812
Epoch  100/2000 Cost: 0.458767
Epoch  200/2000 Cost: 0.457272
Epoch  300/2000 Cost: 0.455790
Epoch  400/2000 Cost: 0.454306
Epoch  500/2000 Cost: 0.452854
Epoch  600/2000 Cost: 0.451392
Epoch  700/2000 Cost: 0.449951
Epoch  800/2000 Cost: 0.448507
Epoch  900/2000 Cost: 0.447074
Epoch 1000/2000 Cost: 0.445660
Epoch 1100/2000 Cost: 0.444234
Epoch 1200/2000 Cost: 0.442840
Epoch 1300/2000 Cost: 0.441430
Epoch 1400/2000 Cost: 0.440049
Epoch 1500/2000 Cost: 0.438660
Epoch 1600/2000 Cost: 0.437285
Epoch 1700/2000 Cost: 0.435926
Epoch 1800/2000 Cost: 0.434561
Epoch 1900/2000 Cost: 0.433213
Epoch 2000/2000 Cost: 0.431865


In [ ]:
model(torch.FloatTensor([[73,80,75]]))

tensor([[151.0500]], grad_fn=<AddmmBackward0>)

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[0.7881, 0.3876, 0.8301]], requires_grad=True), Parameter containing:
 tensor([0.2567], requires_grad=True)]

### - Class로 PyTorch Module 구현

1. 모델을 클래스로 구현

In [ ]:
class LinearRegressionModel(nn.Module): # torch.nn.Module 상속
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self,x): # 자동으로 실행
    return self.linear(x)

model = LinearRegressionModel()

In [ ]:
# 다중 회귀 모델
class MultivariableLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self, x):
    return self.linear(x)

2. 단순 선형 회귀 클래스로 구현

In [ ]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

  def forward(self,x):
    return self.linear(x)

model = LinearRegressionModel()

optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  h = model(x_train)
  cost = F.mse_loss(h, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/2000 Cost: 11.960636
Epoch  100/2000 Cost: 0.022226
Epoch  200/2000 Cost: 0.013735
Epoch  300/2000 Cost: 0.008487
Epoch  400/2000 Cost: 0.005245
Epoch  500/2000 Cost: 0.003241
Epoch  600/2000 Cost: 0.002003
Epoch  700/2000 Cost: 0.001238
Epoch  800/2000 Cost: 0.000765
Epoch  900/2000 Cost: 0.000473
Epoch 1000/2000 Cost: 0.000292
Epoch 1100/2000 Cost: 0.000180
Epoch 1200/2000 Cost: 0.000111
Epoch 1300/2000 Cost: 0.000069
Epoch 1400/2000 Cost: 0.000043
Epoch 1500/2000 Cost: 0.000026
Epoch 1600/2000 Cost: 0.000016
Epoch 1700/2000 Cost: 0.000010
Epoch 1800/2000 Cost: 0.000006
Epoch 1900/2000 Cost: 0.000004
Epoch 2000/2000 Cost: 0.000002
